# Generated by Django 3.2.13 on 2022-05-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energymeasurement',
            old_name='measure_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='energymeasurement',
            old_name='measure_value',
            new_name='energy_value',
        ),
        migrations.AddField(
            model_name='energymeasurement',
            name='energy_source',
            field=models.CharField(default='public grid', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='energymeasurement',
            unique_together={('device', 'date')},
        ),
    ]
