# Generated by Django 3.2.13 on 2022-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0002_auto_20220514_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymeasurement',
            name='date',
            field=models.DateField(),
        ),
    ]
