# Generated by Django 3.2.13 on 2022-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_alter_energymeasurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymeasurement',
            name='calculated_price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
