# Generated by Django 3.2.13 on 2022-05-17 18:41

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0004_alter_energymeasurement_calculated_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energymeasurement',
            name='energy_source',
        ),
        migrations.AddField(
            model_name='energymeasurement',
            name='energy_sources_percentage',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energymeasurement',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_measurements', to='smarthome.device'),
        ),
        migrations.CreateModel(
            name='EnergyDailyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('energy_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('calculated_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('energy_source', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_daily_measurements', to='smarthome.device')),
            ],
            options={
                'unique_together': {('device', 'datetime')},
            },
        ),
    ]
