# Generated by Django 3.2.13 on 2022-05-28 14:29

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [('smarthome', '0006_auto_20220527_2334'), ('smarthome', '0007_energysourcesraport_building'), ('smarthome', '0008_remove_energysourcesraport_energy_prices'), ('smarthome', '0009_auto_20220528_1315')]

    dependencies = [
        ('smarthome', '0005_auto_20220517_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date_from',
            new_name='date_time_from',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='date_to',
            new_name='date_time_to',
        ),
        migrations.RemoveField(
            model_name='energydailymeasurement',
            name='calculated_price',
        ),
        migrations.RemoveField(
            model_name='energydailymeasurement',
            name='energy_source',
        ),
        migrations.RemoveField(
            model_name='energymeasurement',
            name='calculated_price',
        ),
        migrations.RemoveField(
            model_name='energymeasurement',
            name='energy_sources_percentage',
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('device', 'date_time_from')},
        ),
        migrations.CreateModel(
            name='ExchangeEnergyStorageRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('remained_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('date_time_from', models.DateTimeField()),
                ('date_time_to', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_exchange_raports', to='smarthome.building')),
            ],
        ),
        migrations.CreateModel(
            name='EnergySurplusRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('TRANSFER', 'transfer'), ('DEVICES_POWERING', 'devices_powering'), ('BATTERY_CHARGING', 'battery_charging')], max_length=20)),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_time', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_surplus_raports', to='smarthome.building')),
            ],
        ),
        migrations.CreateModel(
            name='EnergySourcesRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_sources', jsonfield.fields.JSONField()),
                ('date_time_from', models.DateTimeField()),
                ('date_time_to', models.DateTimeField()),
                ('building', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='building_energy_sources_raports', to='smarthome.building')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EnergySurplusLossRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date_time', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_surplus_loss_raports', to='smarthome.building')),
            ],
        ),
    ]
