# Generated by Django 3.2.13 on 2022-06-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0007_alter_energysourcesraport_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydailymeasurement',
            name='energy_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energymeasurement',
            name='energy_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energysurpluslossraport',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energysurplusraport',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchangeenergystorageraport',
            name='remained_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exchangeenergystorageraport',
            name='total_value',
            field=models.FloatField(),
        ),
    ]
