# Generated by Django 3.2.13 on 2022-06-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0008_auto_20220602_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotovoltaicsSufficiencyRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sufficiency_percentage', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_photovoltaics_sufficiency_raports', to='smarthome.building')),
            ],
        ),
    ]
