# Generated by Django 3.2.13 on 2022-06-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0009_photovoltaicssufficiencyraport'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='use_exchange_energy',
            field=models.BooleanField(default=False),
        ),
    ]
