# Generated by Django 3.2.13 on 2022-06-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0011_auto_20220614_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='energysurplusraport',
            unique_together={('building', 'date_time', 'value', 'usage_type')},
        ),
    ]
