from smarthome.constants import EnergySource as sources
from smarthome.models import EnergySurplusRaport

photovoltaics_only_home_setups_list = [
    {
        # 1. Energy generated by single photovoltaics is enough to power every device, surplus is transferred to the grid
        "first_window": {
            "receiver_energy": 5,
            "generator_energy": 10,
            "sources": {
                "photovoltaics_used": 5,
                "grid_surplus_used": 0,
                "public_grid_used": 0, 
            },
            "surpluses": {
                sources.GRID_SURPLUS: {
                    "usage_type": EnergySurplusRaport.TRANSFER,
                    "surplus_total_value": 4,
                    "surplus_iteration_value_transfered": 5,
                    "energy_loss": 1,
                },
            }
        }
    },
    {
       # 2. Energy generated by photovoltaics + grid surplus are enough to power every device
       "initial_grid_surplus_value": 6.25,
        "first_window": {
            "receiver_energy": 10,
            "generator_energy": 5,
            "sources": {
                "photovoltaics_used": 5,
                "grid_surplus_used": 5,
                "public_grid_used": 0, 
            },
             "surpluses": {
                sources.GRID_SURPLUS : {
                    "usage_type": EnergySurplusRaport.DEVICES_POWERING,
                    "surplus_total_value": 0,
                    "surplus_iteration_value_transfered": 0,
                },
            }
        }
    },
     {
        # 3. Energy generated by photovoltaics + grid surplus are not enough to power every device, 
        # so its necessary to use also the public grid energy
       "initial_grid_surplus_value": 10,
        "first_window": {
            "receiver_energy": 25,
            "generator_energy": 10,
            "sources": {
                "photovoltaics_used":10,
                "grid_surplus_used": 8,
                "public_grid_used": 7, 
            },
             "surpluses": {
                sources.GRID_SURPLUS : {
                    "usage_type": EnergySurplusRaport.DEVICES_POWERING,
                    "surplus_total_value": 0,
                    "surplus_iteration_value_transfered": 0,
                },
            }
        }
    },
    {
        # 4. Energy generated by photovoltaics is not enough to power every device, there is no grid surplus energy, 
        # so its necessary to use the public grid energy
       "initial_grid_surplus_value": 0,
        "first_window": {
            "receiver_energy": 25,
            "generator_energy": 10,
            "sources": {
                "photovoltaics_used":10,
                "grid_surplus_used": 0,
                "public_grid_used": 15, 
            },
             "surpluses": {
                sources.GRID_SURPLUS: {
                    "usage_type": EnergySurplusRaport.TRANSFER,
                    "surplus_total_value": 0,
                    "surplus_iteration_value_transfered": 0,
                    "energy_loss": 0,
                },
            }
        }
    },
    {
        # 5. There is no photovoltaics, but grid surplus are enough to power every device
       "initial_grid_surplus_value": 10,
        "first_window": {
            "receiver_energy": 5,
            "generator_energy": 0,
            "sources": {
                "photovoltaics_used": 0,
                "grid_surplus_used": 5,
                "public_grid_used": 0, 
            },
             "surpluses": {
                sources.GRID_SURPLUS : {
                    "usage_type": EnergySurplusRaport.DEVICES_POWERING,
                    "surplus_total_value": 3,
                    "surplus_iteration_value_transfered": 0,
                },
            }
        }
    },
    {
        # 6. There is no energy generated by photovoltaics, grid surplus energy is not enough to power every device, 
        # so its necessary to use the public grid energy"""
       "initial_grid_surplus_value": 10,
        "first_window": {
            "receiver_energy": 25,
            "generator_energy": 0,
            "sources": {
                "photovoltaics_used":0,
                "grid_surplus_used": 8,
                "public_grid_used": 17, 
            },
             "surpluses": {
                sources.GRID_SURPLUS : {
                    "usage_type": EnergySurplusRaport.DEVICES_POWERING,
                    "surplus_total_value": 0,
                    "surplus_iteration_value_transfered": 0,
                },
            }
        }
    },
    {
        # 7. There are no photovoltaics and no surplus, so its necessary to use the public grid energy
        "initial_grid_surplus_value": 0,
        "first_window": {
            "receiver_energy": 5,
            "generator_energy": 0,
            "sources": {
                "photovoltaics_used": 0,
                "grid_surplus_used": 0,
                "public_grid_used": 5, 
            },
             "surpluses": {
                sources.GRID_SURPLUS: {
                    "usage_type": EnergySurplusRaport.TRANSFER,
                    "surplus_total_value": 0,
                    "surplus_iteration_value_transfered": 0,
                    "energy_loss": 0,
                },
            }
        }
    }
]  
